---
title: "DSE in a computationally efficient form"
output: html_notebook
---

```{r}
library(tidyverse)
```

upload sample energy-minimized 5nm gold NP coordinates

```{r}
read_delim("../Desktop/pot_test/Min12.5_155.xyz", delim = " ", col_names = F, skip = 9) %>% 
  select(2:4) %>% 
  rename(x=1,y=2,z=3) %>% 
  as.matrix()->atomic_arrangement   #I guess matrix is computationally efficient than tibble


x <- atomic_arrangement[,1]
y <- atomic_arrangement[,2]
z <- atomic_arrangement[,3]

```


calculate all inter-atomic distances (i!=j) and assign them to rij_all
```{r}

rij_all <- 0
count=0

for (i in 1:nrow(atomic_arrangement)) {
  for (j in 1:nrow(atomic_arrangement)) {
    count=count+1
    xi=x[i] #ith atom's positions
    yi=y[i]
    zi=z[i]
    xj=x[j] #jth atom's positions
    yj=y[j]
    zj=z[j]
    rij=sqrt((xi-xj)^2+(yi-yj)^2+(zi-zj)^2)
    rij_all[count] <- rij
  }  
}
rij_all <- rij_all[rij_all!=0] # remove i==j which is zero

```


Do binning for inter-atomic distances, dr=0.001
```{r}
cut(rij_all,breaks = seq(0,50,0.001), right = FALSE)->binned_rij #NP size is around 50 Angstrom

as.tibble(table(binned_rij)) %>% 
  mutate(sep=seq((0.001/2),(50-0.001/2),0.001)) %>%
  select(-1) %>% 
  select(sep,n)->binned_rij_clean

```


Calculate Intensity, I.

```{r}

I <- 0
count=0
N=nrow(atomic_arrangement) # total number of atoms

# atomic scattering factor,f, constants taken from http://lampx.tugraz.at/~hadley/ss1/crystaldiffraction/atomicformfactors/formfactors.php
a <- c(16.8819,18.5913,25.5582,5.86)
b <- c(0.4611,8.6216,1.4826,36.3956)
c <- c(12.0658)

#simulate equation by using 5000 q values between 2 and 4*pi
for (q in seq(2,4*pi,length.out = 2000)) { # wavelength = 1A -> qmax = 4*pi
  count=count+1
  f=sum(a*exp(-b*(q/(4*pi))^2))+c
  # f[count] <- f
  I[count] <- N*f^2 + f^2*sum(binned_rij_clean$n*sin(binned_rij_clean$sep*q)/(binned_rij_clean$sep*q),na.rm = TRUE)
}

```

Finally, plot it.
```{r}

tibble(x=seq(2,4*pi,length.out = 2000),y=I) %>% 
  mutate(x=2*asin(x/(4*pi))*180/pi) %>% # asin() returns radians not degree, so, convert it to degree by multiplying 180/pi. In addition,for 2theta, multiply with 2.
  ggplot(aes(x,y))+
  geom_line(color="black",size=1)+
  scale_x_continuous(n.breaks = 7)+
  labs(y="I",x="2theta, degree")+
  theme_bw()

```


























